#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl enable usbdevice.service || true
    if [ "$1" = "configure" ]; then
        systemctl restart usbdevice.service || true
    fi
fi
exit 0
