#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl stop usbdevice.service || true
    systemctl disable usbdevice.service || true
    systemctl daemon-reload || true
fi
exit 0
