
//-----------------------------------
#define CFG_CE_REG_VERSION_ADDR 0x0000
#define CE_REG_VERSION_OFFSET 0
#define CE_REG_VERSION_MASK 0x000000FF

//-----------------------------------
#define CFG_CE_SOFT_RESET_CFG_ADDR 0x0004
#define CE_FIFO_SOFT_RST_OFFSET 2
#define CE_FIFO_SOFT_RST_MASK 0x00000004
#define CE_RX_SOFT_RST_OFFSET 1
#define CE_RX_SOFT_RST_MASK 0x00000002
#define CE_TX_SOFT_RST_OFFSET 0
#define CE_TX_SOFT_RST_MASK 0x00000001

//-----------------------------------
#define CFG_CE_CRC0_CFG0_ADDR 0x0008
#define CE_CRC0_PARA_FIXED_OFFSET 6
#define CE_CRC0_PARA_FIXED_MASK 0x00000040
#define CE_CRC0_PARA_OFFSET 0
#define CE_CRC0_PARA_MASK 0x0000003F

//-----------------------------------
#define CFG_CE_CRC0_CFG1_ADDR 0x000C
#define CE_CRC0_POLYNOMIAL_OFFSET 0
#define CE_CRC0_POLYNOMIAL_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_CRC1_CFG0_ADDR 0x0010
#define CE_CRC1_PARA_FIXED_OFFSET 6
#define CE_CRC1_PARA_FIXED_MASK 0x00000040
#define CE_CRC1_PARA_OFFSET 0
#define CE_CRC1_PARA_MASK 0x0000003F

//-----------------------------------
#define CFG_CE_CRC1_CFG1_ADDR 0x0014
#define CE_CRC1_POLYNOMIAL_OFFSET 0
#define CE_CRC1_POLYNOMIAL_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_CRC2_CFG0_ADDR 0x0018
#define CE_CRC2_PARA_FIXED_OFFSET 6
#define CE_CRC2_PARA_FIXED_MASK 0x00000040
#define CE_CRC2_PARA_OFFSET 0
#define CE_CRC2_PARA_MASK 0x0000003F

//-----------------------------------
#define CFG_CE_CRC2_CFG1_ADDR 0x001C
#define CE_CRC2_POLYNOMIAL_OFFSET 0
#define CE_CRC2_POLYNOMIAL_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_CRC3_CFG0_ADDR 0x0020
#define CE_CRC3_PARA_FIXED_OFFSET 6
#define CE_CRC3_PARA_FIXED_MASK 0x00000040
#define CE_CRC3_PARA_OFFSET 0
#define CE_CRC3_PARA_MASK 0x0000003F

//-----------------------------------
#define CFG_CE_CRC3_CFG1_ADDR 0x0024
#define CE_CRC3_POLYNOMIAL_OFFSET 0
#define CE_CRC3_POLYNOMIAL_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_CRC4_CFG0_ADDR 0x0028
#define CE_CRC4_PARA_FIXED_OFFSET 6
#define CE_CRC4_PARA_FIXED_MASK 0x00000040
#define CE_CRC4_PARA_OFFSET 0
#define CE_CRC4_PARA_MASK 0x0000003F

//-----------------------------------
#define CFG_CE_CRC4_CFG1_ADDR 0x002C
#define CE_CRC4_POLYNOMIAL_OFFSET 0
#define CE_CRC4_POLYNOMIAL_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_CRC5_CFG0_ADDR 0x0030
#define CE_CRC5_PARA_FIXED_OFFSET 6
#define CE_CRC5_PARA_FIXED_MASK 0x00000040
#define CE_CRC5_PARA_OFFSET 0
#define CE_CRC5_PARA_MASK 0x0000003F

//-----------------------------------
#define CFG_CE_CRC5_CFG1_ADDR 0x0034
#define CE_CRC5_POLYNOMIAL_OFFSET 0
#define CE_CRC5_POLYNOMIAL_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_DBG_STATUS0_ADDR 0x003C
#define CE_DBG_STATUS0_OFFSET 0
#define CE_DBG_STATUS0_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_DBG_STATUS1_ADDR 0x0040
#define CE_DBG_STATUS1_OFFSET 0
#define CE_DBG_STATUS1_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_DBG_STATUS2_ADDR 0x0044
#define CE_DBG_STATUS2_OFFSET 0
#define CE_DBG_STATUS2_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_DBG_STATUS3_ADDR 0x0048
#define CE_DBG_STATUS3_OFFSET 0
#define CE_DBG_STATUS3_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_ALL_CHN_INT_SUMMARY0_ADDR 0x004C
#define CE_ALL_CHN_INT_SUMMARY0_OFFSET 0
#define CE_ALL_CHN_INT_SUMMARY0_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_ALL_CHN_INT_SUMMARY1_ADDR 0x0050
#define CE_ALL_CHN_INT_SUMMARY1_OFFSET 0
#define CE_ALL_CHN_INT_SUMMARY1_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_ALL_CHN_INT_SUMMARY2_ADDR 0x0054
#define CE_ALL_CHN_INT_SUMMARY2_OFFSET 0
#define CE_ALL_CHN_INT_SUMMARY2_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_ALL_CHN_INT_SUMMARY3_ADDR 0x0058
#define CE_ALL_CHN_INT_SUMMARY3_OFFSET 0
#define CE_ALL_CHN_INT_SUMMARY3_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_CE_AXI_FEATURE_SET_ADDR 0x0060
#define CE_RX_AXI_OUTSTANDING_ORDER_OFFSET 3
#define CE_RX_AXI_OUTSTANDING_ORDER_MASK 0x00000008
#define CE_TX_AXI_OUTSTANDING_ORDER_OFFSET 2
#define CE_TX_AXI_OUTSTANDING_ORDER_MASK 0x00000004
#define CE_RX_AXI_OUTSTANDING_ENA_OFFSET 1
#define CE_RX_AXI_OUTSTANDING_ENA_MASK 0x00000002
#define CE_TX_AXI_OUTSTANDING_ENA_OFFSET 0
#define CE_TX_AXI_OUTSTANDING_ENA_MASK 0x00000001

//-----------------------------------
#define CFG_CE_PAUSE_CFG_ADDR 0x00A0
#define CE_TX_PAUSE_STATUS_OFFSET 3
#define CE_TX_PAUSE_STATUS_MASK 0x00000008
#define CE_RX_PAUSE_STATUS_OFFSET 2
#define CE_RX_PAUSE_STATUS_MASK 0x00000004
#define CE_TX_PAUSE_OFFSET 1
#define CE_TX_PAUSE_MASK 0x00000002
#define CE_RX_PAUSE_OFFSET 0
#define CE_RX_PAUSE_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_LINK_ADDR_ADDR 0x1000
#define CHN_RX_LINK_ADDR_OFFSET 0
#define CHN_RX_LINK_ADDR_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_DMA_CHN_TX_LINK_ADDR_ADDR 0x1004
#define CHN_TX_LINK_ADDR_OFFSET 0
#define CHN_TX_LINK_ADDR_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_DMA_CHN_COM_CFG_ADDR 0x1008
#define DMA_CHN_DBG_BUS_SEL_OFFSET 12
#define DMA_CHN_DBG_BUS_SEL_MASK 0x0000F000
#define DMA_CHN_REQ_INDEX_OFFSET 4
#define DMA_CHN_REQ_INDEX_MASK 0x000007F0
#define DMA_CHN_STOP_OFFSET 3
#define DMA_CHN_STOP_MASK 0x00000008
#define DMA_CHN_SOFT_RESET_OFFSET 2
#define DMA_CHN_SOFT_RESET_MASK 0x00000004
#define DMA_CHN_TRANS_TYPE_OFFSET 0
#define DMA_CHN_TRANS_TYPE_MASK 0x00000003

//-----------------------------------
#define CFG_DMA_CHN_TX_CFG_ADDR 0x100C
#define CHN_TX_INT1_ENA_OFFSET 29
#define CHN_TX_INT1_ENA_MASK 0x20000000
#define CHN_TX_INT0_ENA_OFFSET 28
#define CHN_TX_INT0_ENA_MASK 0x10000000
#define CHN_TX_SUSPEND_ST_OFFSET 27
#define CHN_TX_SUSPEND_ST_MASK 0x08000000
#define CHN_TX_RING_CLR_OFFSET 26
#define CHN_TX_RING_CLR_MASK 0x04000000
#define CHN_TX_BURST_ALIGN_EN_OFFSET 25
#define CHN_TX_BURST_ALIGN_EN_MASK 0x02000000
#define CHN_TX_WRAP_BURST_TYPE_OFFSET 21
#define CHN_TX_WRAP_BURST_TYPE_MASK 0x01E00000
#define CHN_TX_DESC_BUS_SDB_OFFSET 20
#define CHN_TX_DESC_BUS_SDB_MASK 0x00100000
#define CHN_TX_DATA_BUS_SDB_OFFSET 19
#define CHN_TX_DATA_BUS_SDB_MASK 0x00080000
#define CHN_TX_PRIORITY_OFFSET 17
#define CHN_TX_PRIORITY_MASK 0x00060000
#define CHN_TX_TRANS_STEP_OFFSET 14
#define CHN_TX_TRANS_STEP_MASK 0x0001C000
#define CHN_TX_DATA_WORD_ORDER_OFFSET 13
#define CHN_TX_DATA_WORD_ORDER_MASK 0x00002000
#define CHN_TX_ADDR_INC_MODE_OFFSET 12
#define CHN_TX_ADDR_INC_MODE_MASK 0x00001000
#define CHN_TX_DATA_WIDTH_OFFSET 10
#define CHN_TX_DATA_WIDTH_MASK 0x00000C00
#define CHN_TX_BIT_ORDER_SEL_OFFSET 9
#define CHN_TX_BIT_ORDER_SEL_MASK 0x00000200
#define CHN_TX_DESC_WORD_ORDER_OFFSET 8
#define CHN_TX_DESC_WORD_ORDER_MASK 0x00000100
#define CHN_TX_BURST_LEN_OFFSET 2
#define CHN_TX_BURST_LEN_MASK 0x000000FC
#define CHN_TX_EB_OFFSET 1
#define CHN_TX_EB_MASK 0x00000002
#define CHN_TX_SUSPEND_OFFSET 0
#define CHN_TX_SUSPEND_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_CFG_ADDR 0x1010
#define CHN_RX_INT1_ENA_OFFSET 29
#define CHN_RX_INT1_ENA_MASK 0x20000000
#define CHN_RX_INT0_ENA_OFFSET 28
#define CHN_RX_INT0_ENA_MASK 0x10000000
#define CHN_RX_SUSPEND_ST_OFFSET 27
#define CHN_RX_SUSPEND_ST_MASK 0x08000000
#define CHN_RX_RING_CLR_OFFSET 26
#define CHN_RX_RING_CLR_MASK 0x04000000
#define CHN_RX_BURST_ALIGN_EN_OFFSET 25
#define CHN_RX_BURST_ALIGN_EN_MASK 0x02000000
#define CHN_RX_WRAP_BURST_TYPE_OFFSET 21
#define CHN_RX_WRAP_BURST_TYPE_MASK 0x01E00000
#define CHN_RX_DESC_BUS_SDB_OFFSET 20
#define CHN_RX_DESC_BUS_SDB_MASK 0x00100000
#define CHN_RX_DATA_BUS_SDB_OFFSET 19
#define CHN_RX_DATA_BUS_SDB_MASK 0x00080000
#define CHN_RX_PRIORITY_OFFSET 17
#define CHN_RX_PRIORITY_MASK 0x00060000
#define CHN_RX_TRANS_STEP_OFFSET 14
#define CHN_RX_TRANS_STEP_MASK 0x0001C000
#define CHN_RX_DATA_WORD_ORDER_OFFSET 13
#define CHN_RX_DATA_WORD_ORDER_MASK 0x00002000
#define CHN_RX_ADDR_INC_MODE_OFFSET 12
#define CHN_RX_ADDR_INC_MODE_MASK 0x00001000
#define CHN_RX_DATA_WIDTH_OFFSET 10
#define CHN_RX_DATA_WIDTH_MASK 0x00000C00
#define CHN_RX_BIT_ORDER_SEL_OFFSET 9
#define CHN_RX_BIT_ORDER_SEL_MASK 0x00000200
#define CHN_RX_DESC_WORD_ORDER_OFFSET 8
#define CHN_RX_DESC_WORD_ORDER_MASK 0x00000100
#define CHN_RX_BURST_LEN_OFFSET 2
#define CHN_RX_BURST_LEN_MASK 0x000000FC
#define CHN_RX_EB_OFFSET 1
#define CHN_RX_EB_MASK 0x00000002
#define CHN_RX_SUSPEND_OFFSET 0
#define CHN_RX_SUSPEND_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_RING_CFG_ADDR 0x1018
#define CHN_RX_RING_FIFO_DEPTH_LOG2_OFFSET 28
#define CHN_RX_RING_FIFO_DEPTH_LOG2_MASK 0xF0000000
#define CHN_RX_RING_HIGH_WATER_THRS_OFFSET 14
#define CHN_RX_RING_HIGH_WATER_THRS_MASK 0x0FFFC000
#define CHN_RX_RING_LOW_WATER_THRS_OFFSET 0
#define CHN_RX_RING_LOW_WATER_THRS_MASK 0x00003FFF

//-----------------------------------
#define CFG_DMA_CHN_TX_RING_CFG_ADDR 0x101C
#define CHN_TX_RING_FIFO_DEPTH_LOG2_OFFSET 28
#define CHN_TX_RING_FIFO_DEPTH_LOG2_MASK 0xF0000000
#define CHN_TX_RING_HIGH_WATER_THRS_OFFSET 14
#define CHN_TX_RING_HIGH_WATER_THRS_MASK 0x0FFFC000
#define CHN_TX_RING_LOW_WATER_THRS_OFFSET 0
#define CHN_TX_RING_LOW_WATER_THRS_MASK 0x00003FFF

//-----------------------------------
#define CFG_DMA_CHN_TX_IDX_INCR_CFG_ADDR 0x1020
#define CHN_TX_RING_WIDX_INCR_POS_OFFSET 14
#define CHN_TX_RING_WIDX_INCR_POS_MASK 0x00004000
#define CHN_TX_RING_WIDX_INCR_OFFSET 0
#define CHN_TX_RING_WIDX_INCR_MASK 0x00003FFF

//-----------------------------------
#define CFG_DMA_CHN_RX_IDX_INCR_CFG_ADDR 0x1024
#define CHN_RX_RING_WIDX_INCR_POS_OFFSET 14
#define CHN_RX_RING_WIDX_INCR_POS_MASK 0x00004000
#define CHN_RX_RING_WIDX_INCR_OFFSET 0
#define CHN_RX_RING_WIDX_INCR_MASK 0x00003FFF

//-----------------------------------
#define CFG_DMA_CHN_RX_RING_FIFO_ST0_ADDR 0x1028
#define CHN_RX_RING_FIFO_RD_IDX_OFFSET 16
#define CHN_RX_RING_FIFO_RD_IDX_MASK 0x1FFF0000
#define CHN_RX_RING_FIFO_DATA_NUM_OFFSET 2
#define CHN_RX_RING_FIFO_DATA_NUM_MASK 0x0000FFFC
#define CHN_RX_RING_FIFO_FULL_OFFSET 1
#define CHN_RX_RING_FIFO_FULL_MASK 0x00000002
#define CHN_RX_RING_FIFO_EMP_OFFSET 0
#define CHN_RX_RING_FIFO_EMP_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_RING_FIFO_ST1_ADDR 0x102C
#define CHN_RX_RING_FIFO_LFO_DATA_NUM_OFFSET 13
#define CHN_RX_RING_FIFO_LFO_DATA_NUM_MASK 0x07FFE000
#define CHN_RX_RING_FIFO_WR_IDX_OFFSET 0
#define CHN_RX_RING_FIFO_WR_IDX_MASK 0x00001FFF

//-----------------------------------
#define CFG_DMA_CHN_TX_RING_FIFO_ST0_ADDR 0x1030
#define CHN_TX_RING_FIFO_RD_IDX_OFFSET 16
#define CHN_TX_RING_FIFO_RD_IDX_MASK 0x1FFF0000
#define CHN_TX_RING_FIFO_DATA_NUM_OFFSET 2
#define CHN_TX_RING_FIFO_DATA_NUM_MASK 0x0000FFFC
#define CHN_TX_RING_FIFO_FULL_OFFSET 1
#define CHN_TX_RING_FIFO_FULL_MASK 0x00000002
#define CHN_TX_RING_FIFO_EMP_OFFSET 0
#define CHN_TX_RING_FIFO_EMP_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_TX_RING_FIFO_ST1_ADDR 0x1034
#define CHN_TX_RING_FIFO_LFO_DATA_NUM_OFFSET 13
#define CHN_TX_RING_FIFO_LFO_DATA_NUM_MASK 0x07FFE000
#define CHN_TX_RING_FIFO_WR_IDX_OFFSET 0
#define CHN_TX_RING_FIFO_WR_IDX_MASK 0x00001FFF

//-----------------------------------
#define CFG_DMA_CHN_INFO_DBG_BUS_ST_ADDR 0x1038
#define CHN_INFO_DBG_BUS_OFFSET 0
#define CHN_INFO_DBG_BUS_MASK 0xFFFFFFFF

//-----------------------------------
#define CFG_DMA_CHN_RX_INT_RAW_ADDR 0x2000
#define CHN_RX_CURR_DESC_PRE_INT_RAW_OFFSET 6
#define CHN_RX_CURR_DESC_PRE_INT_RAW_MASK 0x00000040
#define CHN_RX_BUF_LEN_INVALID_INT_RAW_OFFSET 5
#define CHN_RX_BUF_LEN_INVALID_INT_RAW_MASK 0x00000020
#define CHN_RX_ACK_INT_RAW_OFFSET 4
#define CHN_RX_ACK_INT_RAW_MASK 0x00000010
#define CHN_RX_CURR_DESC_INT_RAW_OFFSET 3
#define CHN_RX_CURR_DESC_INT_RAW_MASK 0x00000008
#define CHN_RX_RING_OVERFLOW_INT_RAW_OFFSET 2
#define CHN_RX_RING_OVERFLOW_INT_RAW_MASK 0x00000004
#define CHN_RX_RING_HIGH_WATER_INT_RAW_OFFSET 1
#define CHN_RX_RING_HIGH_WATER_INT_RAW_MASK 0x00000002
#define CHN_RX_RING_LOW_WATER_INT_RAW_OFFSET 0
#define CHN_RX_RING_LOW_WATER_INT_RAW_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_INT_ST_ADDR 0x2004
#define CHN_RX_CURR_DESC_PRE_INT_ST_OFFSET 6
#define CHN_RX_CURR_DESC_PRE_INT_ST_MASK 0x00000040
#define CHN_RX_BUF_LEN_INVALID_INT_ST_OFFSET 5
#define CHN_RX_BUF_LEN_INVALID_INT_ST_MASK 0x00000020
#define CHN_RX_ACK_INT_ST_OFFSET 4
#define CHN_RX_ACK_INT_ST_MASK 0x00000010
#define CHN_RX_CURR_DESC_INT_ST_OFFSET 3
#define CHN_RX_CURR_DESC_INT_ST_MASK 0x00000008
#define CHN_RX_RING_OVERFLOW_INT_ST_OFFSET 2
#define CHN_RX_RING_OVERFLOW_INT_ST_MASK 0x00000004
#define CHN_RX_RING_HIGH_WATER_INT_ST_OFFSET 1
#define CHN_RX_RING_HIGH_WATER_INT_ST_MASK 0x00000002
#define CHN_RX_RING_LOW_WATER_INT_ST_OFFSET 0
#define CHN_RX_RING_LOW_WATER_INT_ST_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_INT_ENA_ADDR 0x2008
#define CHN_RX_CURR_DESC_PRE_INT_ENA_OFFSET 6
#define CHN_RX_CURR_DESC_PRE_INT_ENA_MASK 0x00000040
#define CHN_RX_BUF_LEN_INVALID_INT_ENA_OFFSET 5
#define CHN_RX_BUF_LEN_INVALID_INT_ENA_MASK 0x00000020
#define CHN_RX_ACK_INT_ENA_OFFSET 4
#define CHN_RX_ACK_INT_ENA_MASK 0x00000010
#define CHN_RX_CURR_DESC_INT_ENA_OFFSET 3
#define CHN_RX_CURR_DESC_INT_ENA_MASK 0x00000008
#define CHN_RX_RING_OVERFLOW_INT_ENA_OFFSET 2
#define CHN_RX_RING_OVERFLOW_INT_ENA_MASK 0x00000004
#define CHN_RX_RING_HIGH_WATER_INT_ENA_OFFSET 1
#define CHN_RX_RING_HIGH_WATER_INT_ENA_MASK 0x00000002
#define CHN_RX_RING_LOW_WATER_INT_ENA_OFFSET 0
#define CHN_RX_RING_LOW_WATER_INT_ENA_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_RX_INT_CLR_ADDR 0x200C
#define CHN_RX_CURR_DESC_PRE_INT_CLR_OFFSET 6
#define CHN_RX_CURR_DESC_PRE_INT_CLR_MASK 0x00000040
#define CHN_RX_BUF_LEN_INVALID_INT_CLR_OFFSET 5
#define CHN_RX_BUF_LEN_INVALID_INT_CLR_MASK 0x00000020
#define CHN_RX_ACK_INT_CLR_OFFSET 4
#define CHN_RX_ACK_INT_CLR_MASK 0x00000010
#define CHN_RX_CURR_DESC_INT_CLR_OFFSET 3
#define CHN_RX_CURR_DESC_INT_CLR_MASK 0x00000008
#define CHN_RX_RING_OVERFLOW_INT_CLR_OFFSET 2
#define CHN_RX_RING_OVERFLOW_INT_CLR_MASK 0x00000004
#define CHN_RX_RING_HIGH_WATER_INT_CLR_OFFSET 1
#define CHN_RX_RING_HIGH_WATER_INT_CLR_MASK 0x00000002
#define CHN_RX_RING_LOW_WATER_INT_CLR_OFFSET 0
#define CHN_RX_RING_LOW_WATER_INT_CLR_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_TX_INT_RAW_ADDR 0x2010
#define CHN_TX_BUFFER_MLEN_VIO_INT_RAW_OFFSET 5
#define CHN_TX_BUFFER_MLEN_VIO_INT_RAW_MASK 0x00000020
#define CHN_TX_ACK_INT_RAW_OFFSET 4
#define CHN_TX_ACK_INT_RAW_MASK 0x00000010
#define CHN_TX_CURR_DESC_INT_RAW_OFFSET 3
#define CHN_TX_CURR_DESC_INT_RAW_MASK 0x00000008
#define CHN_TX_RING_OVERFLOW_INT_RAW_OFFSET 2
#define CHN_TX_RING_OVERFLOW_INT_RAW_MASK 0x00000004
#define CHN_TX_RING_HIGH_WATER_INT_RAW_OFFSET 1
#define CHN_TX_RING_HIGH_WATER_INT_RAW_MASK 0x00000002
#define CHN_TX_RING_LOW_WATER_INT_RAW_OFFSET 0
#define CHN_TX_RING_LOW_WATER_INT_RAW_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_TX_INT_ST_ADDR 0x2014
#define CHN_TX_BUFFER_MLEN_VIO_INT_ST_OFFSET 5
#define CHN_TX_BUFFER_MLEN_VIO_INT_ST_MASK 0x00000020
#define CHN_TX_ACK_INT_ST_OFFSET 4
#define CHN_TX_ACK_INT_ST_MASK 0x00000010
#define CHN_TX_CURR_DESC_INT_ST_OFFSET 3
#define CHN_TX_CURR_DESC_INT_ST_MASK 0x00000008
#define CHN_TX_RING_OVERFLOW_INT_ST_OFFSET 2
#define CHN_TX_RING_OVERFLOW_INT_ST_MASK 0x00000004
#define CHN_TX_RING_HIGH_WATER_INT_ST_OFFSET 1
#define CHN_TX_RING_HIGH_WATER_INT_ST_MASK 0x00000002
#define CHN_TX_RING_LOW_WATER_INT_ST_OFFSET 0
#define CHN_TX_RING_LOW_WATER_INT_ST_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_TX_INT_ENA_ADDR 0x2018
#define CHN_TX_BUFFER_MLEN_VIO_INT_ENA_OFFSET 5
#define CHN_TX_BUFFER_MLEN_VIO_INT_ENA_MASK 0x00000020
#define CHN_TX_ACK_INT_ENA_OFFSET 4
#define CHN_TX_ACK_INT_ENA_MASK 0x00000010
#define CHN_TX_CURR_DESC_INT_ENA_OFFSET 3
#define CHN_TX_CURR_DESC_INT_ENA_MASK 0x00000008
#define CHN_TX_RING_OVERFLOW_INT_ENA_OFFSET 2
#define CHN_TX_RING_OVERFLOW_INT_ENA_MASK 0x00000004
#define CHN_TX_RING_HIGH_WATER_INT_ENA_OFFSET 1
#define CHN_TX_RING_HIGH_WATER_INT_ENA_MASK 0x00000002
#define CHN_TX_RING_LOW_WATER_INT_ENA_OFFSET 0
#define CHN_TX_RING_LOW_WATER_INT_ENA_MASK 0x00000001

//-----------------------------------
#define CFG_DMA_CHN_TX_INT_CLR_ADDR 0x201C
#define CHN_TX_BUFFER_MLEN_VIO_INT_CLR_OFFSET 5
#define CHN_TX_BUFFER_MLEN_VIO_INT_CLR_MASK 0x00000020
#define CHN_TX_ACK_INT_CLR_OFFSET 4
#define CHN_TX_ACK_INT_CLR_MASK 0x00000010
#define CHN_TX_CURR_DESC_INT_CLR_OFFSET 3
#define CHN_TX_CURR_DESC_INT_CLR_MASK 0x00000008
#define CHN_TX_RING_OVERFLOW_INT_CLR_OFFSET 2
#define CHN_TX_RING_OVERFLOW_INT_CLR_MASK 0x00000004
#define CHN_TX_RING_HIGH_WATER_INT_CLR_OFFSET 1
#define CHN_TX_RING_HIGH_WATER_INT_CLR_MASK 0x00000002
#define CHN_TX_RING_LOW_WATER_INT_CLR_OFFSET 0
#define CHN_TX_RING_LOW_WATER_INT_CLR_MASK 0x00000001

//HW module read/write macro
