# BIT0: wifi, BIT1: bt, default=1
fw_sys=5
max_support_ba_bitmap=256
dynbw_enable=1
stats_dump_interval=100000
wq_dbg_lv=1
ps_mode=0
tx_pwr_force_ena=0
tx_pwr_force_dbm=0
tx_ampdu_enable=1
ant_mode=2
coex_ant_mode=2
sco_over_hci=0
