#mac_addr	=	00:03:7f:12:e2:fb
# BIT0: wifi, BIT1: bt, default=1
fw_sys=5
max_support_ba_bitmap=256
dynbw_enable=1
#ht_on=1
#vht_on=1
#he_on=1
#he_ul_on=0
#ldpc_on=1
#stbc_on=1
#gf_rx_on=1
#ap_uapsd_on=1
#sgi=1
#sgi80=1
#use_2040=1
#use_80=1
#custregd=0
#custchan=0
#driver_reg_enable=1
#bfmee=1
#bfmer=1
#mesh=1
#murx=1
#mutx=1
#mutx_on=1
#listen_bcmc=1
#ps_on=1
#tdls=1
#uf=1
#dpsm=1
#ant_div=0
#bfm_enable=1
#loadfw_only=0
#nss1_force=0
stats_dump_interval=100000
#stats_dump_mask=26381
#mcs_map=2
#he_mcs_map=2
#phy_cfg=0
#phy_calib_mode=15
#uapsd_timeout=300
#nss=2
#roc_dur_max=1200
#listen_itv=0
#lp_clk_ppm=20
#amsdu_rx_max=2
#amsdu_maxnb=6
#tx_lft=100
#uapsd_queues=1
#tx_to_bk=0
#tx_to_be=0
#tx_to_vi=0
#tx_to_vo=0
#tx_bundle_max=6
#tx_bundle_expire_us=400
#tx_tcpack_expire_us=5000
wq_dbg_lv=1
#wq_dbg_mod=255
#fw_log_enable=0
ps_mode=0
#drvcc=
#ftl=
#default_p2p_on_for_usb=0
tx_pwr_force_ena=0
tx_pwr_force_dbm=0
tx_ampdu_enable=1
#force_edca_vo=0
#force_ignore_nav=0
#force_pcie_speed=0
#wow_enable=1
#sap_follow_sta_enable=1
#fw_log_path=/var/log/
coex_ant_mode=2
#coex_abort_prop_lv=0
#underrun_adapt_tx_rate=0
