# init_status: 1-day, 2-night
# switch_mode: 1-auto, 2-day, 3-night, 4-time
# light_type:  1-visible, 2-infrared, 3-none, 4-mixed
# light_mode:  1-auto, 2-manual
# calib_mode:  1-d2n, 2-n2d, 3-base, 4-dis

[attr_cfg]
init_status = 1
switch_mode = 1
light_type = 2
light_mode = 2
light_value = 100
en_quick_switch = 0
en_grid_weight = 0
en_auto_n2dth = 0

[params]
d2n_envL_th = 0.04
n2d_envL_th = 0.50
rggain_base = 1.0
bggain_base = 1.0
awbgain_rad = 0.1
awbgain_dis = 0.3
switch_cnts_th = 50

[light_cfg]
en_light_cfg = 0
light_expLow_th = 0.1
light_expHigh_th = 1.0
light_up_speed = 0.15
light_down_speed = 0.2
light_step = 0.1
light_min = 0.1

[switch_test]
switch_en = 0
switch_interval = 100

[lock_cfg]
lock_en = 1
lock_interval = 0

[starlight_cfg]
mode_en = 0
mid_trans_en = 0
low_envL_th = 0.8
high_envL_th = 1.0

[calib_cfg]
calib_en = 0
calib_mode = 1
